apiVersion: v1
kind: Service
metadata:
  name: candy-crush
  namespace: games
spec:
  selector:
    app: candy-crush
  type: ClusterIP
  ports:
  - name: candy-crush
    protocol: TCP
    port: 8090
    targetPort: 80
